name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Build pacakages [main]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/heads/main'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build packages
        run: |
          pip install wheel
          mkdir dist/
          python ./autoloader/setup.py bdist_wheel -d dist/
          python ./majordomo/setup.py bdist_wheel -d dist/
          python ./pedant/setup.py bdist_wheel -d dist/


      - name: Upload autoloader
        uses: actions/upload-artifact@v2
        with:
          name: autoloader
          path: ./dist/
      
      - name: Upload majordomo
        uses: actions/upload-artifact@v2
        with:
          name: majordomo
          path: ./dist/
      
      - name: Upload pedant
        uses: actions/upload-artifact@v2
        with:
          name: pedant
          path: ./dist/

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          automatic_release_tag: "0.2.${{ github.run_id }}"
          prerelease: false
          title: "Thor Packages 0.2.${{ github.run_id }}"
          files: |
            ./dist/autoloader-*.whl
            ./dist/majordomo-*.whl
            ./dist/pedant-*.whl